name: harvey
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python=3
  - matplotlib
  - numpy
  - scipy
  - docutils
  - pip
  - gfortran
  - doxygen
  - graphviz
  - ghp-import
  - jupyter
  - pip:
      - robotframework
      - git+https://github.com/Feneric/doxypypy
