[project]
name = "harvey"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "docutils>=0.22.4",
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
    "robotframework>=7.4.1",
    "scipy>=1.17.0",
]
